# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine
GAMEPROJECTFILE =/home/jirka/Dokumenty/Unreal Projects/HFTerrainSimulation/HFTerrainSimulation.uproject

TARGETS = \
	HFTerrainSimulation-Linux-DebugGame  \
	HFTerrainSimulation-Linux-Shipping  \
	HFTerrainSimulation \
	HFTerrainSimulationEditor-Linux-DebugGame  \
	HFTerrainSimulationEditor-Linux-Shipping  \
	HFTerrainSimulationEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend HFTerrainSimulationEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug HFTerrainSimulationEditor-Linux-Debug


HFTerrainSimulation-Linux-DebugGame:
	 $(PROJECTBUILD) HFTerrainSimulation Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

HFTerrainSimulation-Linux-Shipping:
	 $(PROJECTBUILD) HFTerrainSimulation Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

HFTerrainSimulation:
	 $(PROJECTBUILD) HFTerrainSimulation Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

HFTerrainSimulationEditor-Linux-DebugGame:
	 $(PROJECTBUILD) HFTerrainSimulationEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

HFTerrainSimulationEditor-Linux-Shipping:
	 $(PROJECTBUILD) HFTerrainSimulationEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

HFTerrainSimulationEditor:
	 $(PROJECTBUILD) HFTerrainSimulationEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
